service: w09-reko-iot 

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "rekognition:*"
        Resource:
          - "*"
      - Effect: "Allow"
        Action:
          - "s3:*"
        Resource:
          - "*"
      - Effect: "Allow"
        Action:
          - "iot:*"
        Resource:
          - "*"

functions:
  reko:
    handler: handler.run
    events:
      - s3: w09-reko-iot
